#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Apr 29 20:48:20 PDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Better MC - Medium
